-- Propiedad
ALTER TABLE PROPIEDAD  ADD DIVIDENDO DOUBLE AFTER TIPOPROPIEDAD_ID;

-- Modificacion de Tablas de EXPENSAS
-- Expensa   
ALTER TABLE EXPENSA  ADD DEUDA_PREVIA DOUBLE NOT NULL DEFAULT 0;
ALTER TABLE EXPENSA  ADD INT_SEGUNDO_VTO DOUBLE NOT NULL DEFAULT 0;
-- Expensa Liquidacion
DROP TABLE EXPENSA_LIQUIDACION;
-- Expensa Cobro
ALTER TABLE EXPENSA_COBRO  ADD MONTOPAGO DOUBLE NOT NULL;
DROP INDEX EXPENSA_COBRO_FK1 ON EXPENSA_COBRO;
CREATE UNIQUE INDEX EXPENSA_COBRO_UQ1 ON EXPENSA_COBRO (EXPENSA_ID ASC);