-- -----------------------------------------------------
-- Table PLAN
-- -----------------------------------------------------
CREATE TABLE PLAN (
	ID INTEGER NOT NULL,
	CANTIDAD_COUTAS INTEGER NOT NULL,
	FECHA DATETIME NOT NULL,
	MONTO DOUBLE PRECISION NOT NULL,
	SALDO_INTERESES DOUBLE PRECISION NOT NULL,
	SALDO_PLAN DOUBLE PRECISION NOT NULL,
	ORD_EXT VARCHAR(255) NOT NULL,
	RESPONSABLE_DNI INTEGER NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE (ORD_EXT, FECHA, RESPONSABLE_DNI),
	CONSTRAINT PLAN_FK1 FOREIGN KEY (RESPONSABLE_DNI) REFERENCES RESPONSABLE (DNI)
) ENGINE=InnoDB;

CREATE INDEX PLAN_FK1 ON PLAN (RESPONSABLE_DNI);

-- -----------------------------------------------------
-- Table PLAN_EXPENSA_COBRO
-- -----------------------------------------------------
CREATE TABLE PLAN_EXPENSA_COBRO (
	PLAN_ID INTEGER NOT NULL,
	COBRO_ID INTEGER NOT NULL,
	PRIMARY KEY (PLAN_ID, COBRO_ID),
	UNIQUE (COBRO_ID),
        CONSTRAINT PLAN_EXPENSA_COBRO_FK1 FOREIGN KEY (COBRO_ID) REFERENCES EXPENSA_COBRO (ID),
	CONSTRAINT PLAN_EXPENSA_COBRO_FK2 FOREIGN KEY (PLAN_ID) REFERENCES PLAN (ID)
) ENGINE=InnoDB;

CREATE INDEX PLAN_EXPENSA_COBRO_FK1 ON PLAN_EXPENSA_COBRO (COBRO_ID);
CREATE INDEX PLAN_EXPENSA_COBRO_FK2 ON PLAN_EXPENSA_COBRO (PLAN_ID);

-- -----------------------------------------------------
-- Table CUOTA
-- -----------------------------------------------------
CREATE TABLE CUOTA (
    ID INTEGER NOT NULL,
    ATRASADO BIT,
    INTERES_2VTO DOUBLE PRECISION,
    INTERESES DOUBLE PRECISION,
    MONTO DOUBLE PRECISION,
    NUMERO_CUOTA INTEGER,
    PLAN_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (NUMERO_CUOTA, PLAN_ID),
    CONSTRAINT CUOTA_FK1 FOREIGN KEY (PLAN_ID) REFERENCES PLAN (ID)
) ENGINE=InnoDB;

CREATE INDEX CUOTA_FK1 ON CUOTA (PLAN_ID);

-- -----------------------------------------------------
-- Table CUOTA_COBRO
-- -----------------------------------------------------
CREATE TABLE CUOTA_COBRO (
    ID INTEGER NOT NULL,
    COMPROBANTE VARCHAR(255) NOT NULL,
    FECHA DATETIME NOT NULL,
    CUOTA_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (CUOTA_ID),
    CONSTRAINT CUOTA_COBRO_FK1 FOREIGN KEY (CUOTA_ID) REFERENCES CUOTA (ID)
) ENGINE=InnoDB;

CREATE INDEX CUOTA_COBRO_FK1 ON CUOTA_COBRO (CUOTA_ID);
