use administracionedificios;

alter table EXPENSA
   modify column INTERESES DOUBLE NOT NULL DEFAULT 0,
   add column DEUDA_PREVIA DOUBLE NOT NULL DEFAULT 0,
   add column INT_SEGUNDO_VTO DOUBLE NOT NULL DEFAULT 0;

drop table EXPENSA_LIQUIDACION;

alter table EXPENSA_COBRO
   add column MONTOPAGO DOUBLE NOT NULL after RESPONSABLECOBRO_ID,
   drop index EXPENSA_COBRO_FK1,
   add UNIQUE INDEX EXPENSA_COBRO_FK1 (EXPENSA_ID ASC);
